apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rx2nwk1yb-dotnet-basic
  janus-idp.io/tekton: rx2nwk1yb-dotnet-basic
  backstage.io/kubernetes-id: rx2nwk1yb-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rx2nwk1yb-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
